### ISSUE TITLE
Can not mock two routes at once.

### ISSUE THREAD

**Issue by cmcculloh-kr** [sheremet-va/vi-fetch#9]
I'm trying to mock up two routes at once, but it is throwing an error.

Here's a reduced test case:

`reducedTestCase.js`:
```javascript
const doFetches = async () => {
	await fetch('https://api.com/v1/apples').catch((error) => console.error(error));
	await fetch('https://api.com/v1/oranges').catch((error) => console.error(error));
};

export { doFetches };
```

`reducedTestCase.test.js`:
```javascript
import { afterEach, beforeEach, expect, describe, it, vi } from 'vitest';

import { doFetches } from './reducedTestCase.js';

import { mockFetch, mockGet } from 'vi-fetch';

describe('fruit', () => {
	beforeEach(() => {
		mockFetch.clearAll();
	});
	afterEach(() => {
		vi.clearAllMocks();
	});
	it('can mock two routes', async () => {
		const mock = mockGet('https://api.com/v1/apples').willResolve([{ count: 33 }]);
		const mock2 = mockGet('https://api.com/v1/oranges').willResolve([{ count: 34 }]);
		await doFetches();
		expect(mock).toHaveFetched();
		expect(mock2).toHaveFetched();
	});
});
```

The second mock overwrites the first and you get the following error:
```
Error: fetch is not defined. tried fetching "https://api.com/v1/apples"
    at originalFetch (node_modules/vi-fetch/dist/api.js:97:11)
    at obj.<computed> (node_modules/vi-fetch/dist/api.js:105:14)
    at spy (node_modules/tinyspy/dist/index.js:48:26)
    at spy (node_modules/tinyspy/dist/index.js:48:26)
    at spy (node_modules/tinyspy/dist/index.js:48:26)
```

**Comment by cmcculloh-kr** [comment]
I also tried using regex & `willDo` to see if there was a way I could inspect the URL and return my desired value depending on which route they tried. That didn't work either...

```javascript
const doFetches = async () => {
	await fetch('/apples').catch((error) => console.error(error));
	await fetch('/oranges').catch((error) => console.error(error));
};

import { afterEach, beforeEach, expect, describe, it, vi } from 'vitest';

import { mockFetch, mockGet } from 'vi-fetch';

describe('fruit', () => {
	beforeEach(() => {
		mockFetch.clearAll();
	});
	afterEach(() => {
		vi.clearAllMocks();
	});
	it('can mock two routes', async () => {
		const mock = mockGet(/\/\S+/i, false).willDo((url) => {
			console.log('url', url);
			return { body: [{ count: 33 }] };
		});
		await doFetches();
		expect(mock).toHaveFetched();
	});
});
```

Resulted in:
```
stderr | src/lib/__tests__/mockTwoRoutes.test.js > fruit > can mock two routes
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:372:5)
    at URL.onParseError (node:internal/url:553:9)
    at new URL (node:internal/url:629:5)
    at getDataFromMockResult (file:///Users/cmcculloh/Projects/dlux-labs-site/node_modules/vi-fetch/dist/api.js:87:35)
    at obj.<computed> (file:///Users/cmcculloh/Projects/dlux-labs-site/node_modules/vi-fetch/dist/api.js:110:61)
    at spy (file:///Users/cmcculloh/Projects/dlux-labs-site/node_modules/tinyspy/dist/index.js:48:26)
    at doFetches (/Users/cmcculloh/Projects/dlux-labs-site/src/lib/__tests__/mockTwoRoutes.test.js:2:8)
    at /Users/cmcculloh/Projects/dlux-labs-site/src/lib/__tests__/mockTwoRoutes.test.js:24:9
    at /Users/cmcculloh/Projects/dlux-labs-site/node_modules/vitest/dist/chunk-runtime-chain.46442ffe.js:1952:36
    at /Users/cmcculloh/Projects/dlux-labs-site/node_modules/vitest/dist/chunk-runtime-chain.46442ffe.js:1848:26 {
  input: '/apples',
  code: 'ERR_INVALID_URL'
}
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:372:5)
    at URL.onParseError (node:internal/url:553:9)
    at new URL (node:internal/url:629:5)
    at getDataFromMockResult (file:///Users/cmcculloh/Projects/dlux-labs-site/node_modules/vi-fetch/dist/api.js:87:35)
    at obj.<computed> (file:///Users/cmcculloh/Projects/dlux-labs-site/node_modules/vi-fetch/dist/api.js:110:61)
    at spy (file:///Users/cmcculloh/Projects/dlux-labs-site/node_modules/tinyspy/dist/index.js:48:26)
    at doFetches (/Users/cmcculloh/Projects/dlux-labs-site/src/lib/__tests__/mockTwoRoutes.test.js:3:8)
    at async /Users/cmcculloh/Projects/dlux-labs-site/src/lib/__tests__/mockTwoRoutes.test.js:24:3
    at async runTest (/Users/cmcculloh/Projects/dlux-labs-site/node_modules/vitest/dist/vendor-entry.225630f2.js:891:5)
    at async runSuite (/Users/cmcculloh/Projects/dlux-labs-site/node_modules/vitest/dist/vendor-entry.225630f2.js:959:13) {
  input: '/oranges',
  code: 'ERR_INVALID_URL'
}
```

**Comment by cmcculloh-kr** [comment]
Well. This worked:

```
const doFetches = async () => {
	await fetch('https://localhost:3000/apples').catch((error) => console.error(error));
	await fetch('https://localhost:3000/apples?v=one').catch((error) => console.error(error));
};

import { afterEach, beforeEach, expect, describe, it, vi } from 'vitest';

import { mockFetch, mockGet } from 'vi-fetch';

describe('fruit', () => {
	beforeEach(() => {
		mockFetch.clearAll();
	});
	afterEach(() => {
		vi.clearAllMocks();
	});
	it('can mock two routes', async () => {
		const mock = mockGet('https://localhost:3000/apples', false).willDo((url) => {
			console.log('url', url);
			return { body: [{ count: 33 }] };
		});
		await doFetches();
		expect(mock).toHaveFetched();
	});
});
```

When I'm using `.willResolve` it doesn't make me fully qualify the URL. The code I am testings does not fully qualify the URL, so this isn't really a solution for me either.

**Comment by sheremet-va** [comment]
Did you try using `setOptions`?

```ts
mockFetch.setOptions({
  baseUrl: 'https://api.com/v1',
});
const mock = mockGet('/apples').willResolve([{ count: 33 }]);
const mock2 = mockGet('/oranges').willResolve([{ count: 34 }]);
```

- Your `fetch` call must have full url (with `https/http`)
- `mockGet` should contain full url, including query (you can pass `false` to second argument to allow any query)
- You can use `mockFetch.setOptions` to set `baseUrl`, vi-fetch will concatenate it with the first argument, and check when `fetch` is called.
- If you need to define different behaviour for the SAME url, use `willDo`, or chain `willResolveOnce().willResolveOnce()`
